name: nutrition_ai_module
description: Passio Nutrition AI Module for Flutter. Supports Android and iOS.
version: 3.1.0
homepage: https://www.passio.ai
repository: https://github.com/Passiolife/Flutter-Nutrition-AI-Module
issue_tracker: https://github.com/Passiolife/Flutter-Nutrition-AI-Module/issues

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/equatable
  # Being able to compare objects in Dart often involves having to override the == operator as well as hashCode.
  equatable: ^2.0.5

  # https://pub.dev/packages/flutter_bloc
  # It is a design pattern which helps separate the presentation layer from the business logic.
  flutter_bloc: ^8.1.6

  # https://pub.dev/packages/flutter_local_notifications
  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^17.1.2

  # https://pub.dev/packages/flutter_screenutil
  # A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.9.3

  # https://pub.dev/packages/flutter_slidable
  # A Flutter implementation of slidable list item with directional slide actions that can be dismissed.
  flutter_slidable: ^3.1.0

  # https://pub.dev/packages/flutter_speed_dial
  # Flutter package to render a Material Design Speed Dial.
  flutter_speed_dial: ^7.0.0

  # https://pub.dev/packages/flutter_svg
  # Draw SVG files using Flutter.
  flutter_svg: ^2.0.10+1

  # https://pub.dev/packages/flutter_timezone
  # A flutter plugin for getting the local timezone of the OS.
  flutter_timezone: ^1.0.8

  # https://pub.dev/packages/get_it
  # This is a simple Service Locator for Dart and Flutter projects.
  get_it: ^7.7.0

  # https://pub.dev/packages/intl
  # Provides internationalization and localization facilities
  intl: ^0.19.0

  # https://pub.dev/packages/json_annotation
  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.9.0

  # https://pub.dev/packages/json_serializable
  # Provides Dart Build System builders for handling JSON.
  json_serializable: ^6.8.0

  # https://pub.dev/packages/loading_indicator
  # A collection of out of the box loading animations written in pure dart, no extra dependency
  loading_indicator: ^3.1.1

  # https://pub.dev/packages/nutrition_ai
  # When integrated into your app the SDK provides you with food recognition and nutrition assistant technology.
  nutrition_ai: ^3.1.0

  # https://pub.dev/packages/path
  # A comprehensive, cross-platform path manipulation library for Dart.
  path: ^1.9.0

  # https://pub.dev/packages/permission_handler
  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  permission_handler: ^11.3.1

  # https://pub.dev/packages/shared_preferences
  # Wraps platform-specific persistent storage for simple data (NSUserDefaults on iOS and macOS, SharedPreferences on Android, etc.).
  shared_preferences: ^2.2.3

  # https://pub.dev/packages/shimmer
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0

  # https://pub.dev/packages/simple_gesture_detector
  # Required for table_calendar functionality.
  # Easy to use, reliable and lightweight gesture detector for Flutter apps. Exposes simple API to react to basic gestures.
  simple_gesture_detector: ^0.2.1

  # https://pub.dev/packages/speech_to_text
  # A library that exposes device specific speech recognition capability.
  speech_to_text: ^6.6.2

  # https://pub.dev/packages/sqflite
  # SQLite plugin for Flutter.
  sqflite: ^2.3.3+1

  # https://pub.dev/packages/syncfusion_flutter_charts
  # The Flutter Charts package
  syncfusion_flutter_charts: ^25.2.7

  # https://pub.dev/packages/timezone
  # This package provides the IANA time zone database and time zone aware DateTime class, TZDateTime.
  timezone: ^0.9.3

  # https://pub.dev/packages/url_launcher
  # A Flutter plugin for launching a URL.
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # https://pub.dev/packages/build_runner
  # The build_runner package provides a concrete way of generating files using Dart code.
  build_runner: ^2.4.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
